callbacks:
  early_stopping:
    monitor: "val_f1_score"
    mode: "max"
    patience: 5

  model_checkpoint:
    monitor: "val_f1_score"
    mode: "max"
    save_top_k: 2

  accuracy_checkpoint:
    monitor: "val_accuracy"
    mode: "max"
    save_top_k: 2

logging:
  tensorboard_dir: "tb_logs/"
  base_name: "vit_base_16"
