data:
  train_csv_path: "C:\\Anomaly_detection_3D_printing\\data\\csv_files\\train_gray_black_resized.csv"
  val_csv_path: "C:\\Anomaly_detection_3D_printing\\data\\csv_files\\val_gray_black_resized.csv"

transforms:
  normalization:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
  augmentation:
    random_horizontal_flip: true
    rotation_degrees: 30
    grayscale_prob: 0.2
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
